name: Add new issues to project board

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: Main
          column: Need to Look Into
          repo-token: ${{ secrets.GITHUB_TOKEN }}
